language: scala
scala:
    - 2.10.0
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
before_cache:
    - find $HOME/.sbt -name "*.lock" -delete
    - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
